/*
* Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:   
* This file was autogenerated by rpcgen, but should be modified by the developer.
* Make sure you don't use the -component_mod flag in future or this file will be overwritten.
* Fri Sep 12 12:11:08 2003
*
*/




#ifndef __CSMOBSTER_H__
#define __CSMOBSTER_H__


/****************************************************************************************
 * 
 * Local Includes
 * 
 ***************************************************************************************/
#include "mobster.h"
#include "../MobileTermination/CPhone.h"


/****************************************************************************************
 * 
 * Definition: CSMobster
 * 
 ***************************************************************************************/
class CSMobster
{
public:
	// Standard Methods
	CSMobster();
	~CSMobster();
	int GetKey();
	void SetKey( int aKey );

	// RPC Service Methods
	int cstr_startdevice( TDeviceDesc aArgs );
	int dstr_removedevice( int aArgs, int *aDeleteInstance );
	TDeviceDesc getdeviceinfo( int aArgs );
	TVarData getdevicelog( int aArgs );
	int stopdevice( int aArgs );
	int setremoteuuaddress( TUUAddress aArgs );

	// Added methods that the service accesses
	int settesocket( int aSock );

private:
	int iKey;
	TDeviceDesc iDeviceDesc;
	CPhone iPhone;
};

#endif
