/*
* Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:   
* This file was autogenerated by rpcgen, but should be modified by the developer.
* Make sure you don't use the -component_mod flag in future or this file will be overwritten.
* Fri Sep 19 13:14:28 2003
*
*/




#ifndef __CSVCMOBSTER_H__
#define __CSVCMOBSTER_H__


/****************************************************************************************
 * 
 * Local Includes
 * 
 ***************************************************************************************/
#include "mobster.h"
#include "CSMobster.h"
#include "CComponentManager.h"


/****************************************************************************************
 * 
 * Definition: CSvcMobster
 * 
 ***************************************************************************************/
class CSvcMobster
{
public:
	static int GetInstanceKeyFromArgs( int aMethod, void *aArgs );
	static int SetError( int aMethod, void *aArgs, int aError );
	static int StartRPCService( CComponentManager<CSMobster> *aComponentManager, TChannelAddress *aArg );
	static int StopRPCService();

private:
	static void WaitForConnectionsFromTerminalEmulations( void );
	static void ConnectClientToMobileTermination( int aSock);
};

#endif
