/*
* Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:   
* This file was autogenerated by rpcgen, but should be modified by the developer.
* Make sure you don't use the -component_mod flag in future or this file will be overwritten.
* Tue Oct 28 11:38:50 2003
* System Includes
*
*/




#include <stdio.h>


/****************************************************************************************
 * 
 * Local Includes
 * 
 ***************************************************************************************/
#include "CSvcHostexecute.h"
#include "CSHostexecute.h"


/****************************************************************************************
 * 
 * Implementation
 * 
 ***************************************************************************************/
CSHostexecute::CSHostexecute()
{
}

CSHostexecute::~CSHostexecute()
{
}

int CSHostexecute::GetKey()
{
	return iKey;
}

void CSHostexecute::SetKey( int aKey )
{
	iKey = aKey;
}
