/*
* Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:   
* This file was autogenerated by rpcgen, but should be modified by the developer.
* Make sure you don't use the -component_mod flag in future or this file will be overwritten.
* Tue Oct 28 10:15:13 2003
*
*/




#ifndef __CSVCHOSTEXECUTE_H__
#define __CSVCHOSTEXECUTE_H__


/****************************************************************************************
 * 
 * Local Includes
 * 
 ***************************************************************************************/
#include "hostexecute.h"
#include "CSHostexecute.h"
#include "CComponentManager.h"


/****************************************************************************************
 * 
 * Definition: CSvcHostexecute
 * 
 ***************************************************************************************/
class CSvcHostexecute
{
public:
	/* standard methods */
	static int GetInstanceKeyFromArgs( int aMethod, void *aArgs );
	static int SetError( int aMethod, void *aArgs, int aError );
	static int GetError( int aMethod, void *aArgs );
	static int StartRPCService( CComponentManager<CSHostexecute> *aComponentManager, TStartupInfo *aArg );
	static int StopRPCService();

	/* custom methods */
	static TExecuteResult st_executecommand( TExecuteRequest aArgs );
};

#endif
