//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:     
//
LOAD_SUITE TS_SockBench.dll
LOAD_SUITE NEControlST.dll
pause_at_end

PRINT -------------------------------------------------------------------------
PRINT 
PRINT  Establish a PPP connection and connect to a remote chargen server (TCP)
PRINT 
PRINT -------------------------------------------------------------------------
PRINT 


////////////////////////////////////////////////////////////////////////////////////////////////////
//
// Start the sockbench server
//
////////////////////////////////////////////////////////////////////////////////////////////////////
RUN_TEST_STEP 100, TS_SockBench, OpenServer


////////////////////////////////////////////////////////////////////////////////////////////////////
//
// Run some tests
//
////////////////////////////////////////////////////////////////////////////////////////////////////
RUN_TEST_STEP -1, NEControlST, StartUseCase,	c:\sti.0006.ini 
RUN_TEST_STEP -1, NEControlST, WaitForSignal,	c:\sti.0006.ini 
RUN_TEST_STEP -1, NEControlST, SetDeviceID,		c:\sti.0006.ini 
RUN_TEST_STEP 100, TS_SockBench, TestSockBench,	c:\sti.0006.ini
RUN_TEST_STEP -1, NEControlST, Signal,			c:\sti.0006.ini 
RUN_TEST_STEP -1, NEControlST, Rendezvous,		c:\sti.0006.ini 
TEST_COMPLETE
RUN_TEST_STEP -1, NEControlST, EndUseCase,		c:\sti.0006.ini    
TEST_COMPLETE 


////////////////////////////////////////////////////////////////////////////////////////////////////
//
// Done
//
////////////////////////////////////////////////////////////////////////////////////////////////////
RUN_TEST_STEP 100, TS_SockBench, CloseServer