/*
* Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  
* This file was autogenerated by rpcgen, but should be modified by the developer.
* Make sure you don't use the -component_mod flag in future or this file will be overwritten.
* Tue Nov 16 15:19:57 2004
* System Includes
*
*/



#include <stdio.h>
#include <assert.h>


/****************************************************************************************
 * 
 * Local Includes
 * 
 ***************************************************************************************/
#include "CSvcGenericstub.h"
#include "CSGenericstub.h"

/****************************************************************************************
 * 
 * Implementation
 * 
 ***************************************************************************************/
CSGenericstub::CSGenericstub()
	: iKey(0), iService(NULL)
{
	iService = Service();
	assert( iService != NULL );
}

CSGenericstub::~CSGenericstub()
{
	if( iService != NULL )
	{
		delete iService;
		iService = NULL;
	}
}

int CSGenericstub::GetKey()
{
	return iKey;
}

void CSGenericstub::SetKey( int aKey )
{
	iKey = aKey;
}


/****************************************************************************************
 * 
 * PUBLIC FUNCTION: cstr_startprocess
 * 
 ***************************************************************************************/
int CSGenericstub::cstr_startprocess(char * /*aArgs*/)
{
	int rv;
	rv = ERR_NONE;
	return rv;
}


/****************************************************************************************
 * 
 * PUBLIC FUNCTION: dstr_removeprocess
 * 
 ***************************************************************************************/
int CSGenericstub::dstr_removeprocess( int /*aArgs*/, int * /*aDeleteInstance*/)
{
	int rv;
	rv = ERR_NONE;
	return rv;
}


/****************************************************************************************
 * 
 * PUBLIC FUNCTION: run_command
 * 
 ***************************************************************************************/
int CSGenericstub::run_command( TCall aArgs )
{
	CCall call( aArgs );
	if( iService != NULL )
		return iService->RunCommand( call );
	else
		return ERR_SERVICE_NOT_RUNNING;
}

/****************************************************************************************
 * 
 * PUBLIC FUNCTION: Setup
 *                   Delegate to the user derived service
 * 
 ***************************************************************************************/
bool CSGenericstub::Setup()
{
	bool ret = false;
	if( iService != NULL )
		ret = iService->Setup();
	return ret;
}
