/*
* Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  
* This file was autogenerated by rpcgen, but should be modified by the developer.
* Make sure you don't use the -component_mod flag in future or this file will be overwritten.
* Tue Nov 16 15:19:57 2004
* System Includes
*
*/



#include <stdio.h>


/****************************************************************************************
 * 
 * Local Includes
 * 
 ***************************************************************************************/
#include "CSvcGenericstub.h"
#include "GenericStub.h"


/****************************************************************************************
 * 
 * File-scope variables
 * 
 ***************************************************************************************/
static CComponentManager<CSGenericstub> *iComponentManager;


/****************************************************************************************
 * 
 * Implementation
 * 
 ***************************************************************************************/


/****************************************************************************************
 * 
 * PUBLIC: GetInstanceKeyFromArgs
 * 
 ***************************************************************************************/
int CSvcGenericstub::GetInstanceKeyFromArgs( int aMethod, void * /*aArgs*/ )
{
	int rv;
	switch( aMethod ) {
	case DSTR_REMOVEPROCESS:
	case RUN_COMMAND:
	default:
		rv = ERR_INVALID_METHOD;
		break;
	}
	return rv;
}


/****************************************************************************************
 * 
 * PUBLIC: SetError
 * 
 ***************************************************************************************/
int CSvcGenericstub::SetError( int aMethod, void * /*aArgs*/, int /*aError*/)
{
	int rv;
	switch( aMethod ) {
	case LIST_CONNECTIONS:
	default:
		rv = ERR_INVALID_METHOD;
		break;
	}
	return rv;
}


/****************************************************************************************
 * 
 * PUBLIC: GetError
 * 
 ***************************************************************************************/
int CSvcGenericstub::GetError( int aMethod, void * /*aArgs*/)
{
	int rv = ERR_NONE;
	switch( aMethod ) {
	case LIST_CONNECTIONS:
	default:
		assert( "!INVALID CALL" );
		break;
	}
	return rv;
}


/****************************************************************************************
 * 
 * PUBLIC: StartRPCService
 * 
 ***************************************************************************************/
int CSvcGenericstub::StartRPCService( CComponentManager<CSGenericstub> *aComponentManager, TStartupInfo * /*aArg*/ )
{
	assert( iComponentManager == NULL );
	iComponentManager = aComponentManager;
	return ERR_NONE;
}


/****************************************************************************************
 * 
 * PUBLIC: StopRPCService
 * 
 ***************************************************************************************/
int CSvcGenericstub::StopRPCService()
{
	iComponentManager = NULL;
	return ERR_NONE;
}
