/*
* Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:   
* This file was autogenerated by rpcgen, but should be modified by the developer.
* Make sure you don't use the -component_mod flag in future or this file will be overwritten.
* Mon Nov 24 15:19:48 2003
* System Includes
*
*/




#include <stdio.h>


/****************************************************************************************
 * 
 * Local Includes
 * 
 ***************************************************************************************/
#include "CSvcUuinterface.h"
#include "CSUuinterface.h"


/****************************************************************************************
 * 
 * Implementation
 * 
 ***************************************************************************************/
CSUuinterface::CSUuinterface()
{
}

CSUuinterface::~CSUuinterface()
{
}

int CSUuinterface::GetKey()
{
	return iKey;
}

void CSUuinterface::SetKey( int aKey )
{
	iKey = aKey;
}
