/*
* Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  
* This file was autogenerated by rpcgen, but should be modified by the developer.
* Make sure you don't use the -component_mod flag in future or this file will be overwritten.
* Tue Nov 16 15:19:57 2004
*
*/



#ifndef __CSGENERICSTUB_H__
#define __CSGENERICSTUB_H__

/****************************************************************************************
 * 
 * Local Includes
 * 
 ***************************************************************************************/
#include "GenericStub.h"
#include "CService.h"

/****************************************************************************************
 * 
 * Definition: CSGenericstub
 * 
 ***************************************************************************************/
class CSGenericstub
{
public:
	// Standard Methods
	CSGenericstub();
	~CSGenericstub();
	int GetKey();
	void SetKey( int aKey );

	// RPC Service Methods
	int cstr_startprocess( char *aArgs );
	int dstr_removeprocess( int aArgs, int *aDeleteInstance );
	int run_command( TCall aArgs );

	// Setup the service (if required)
	bool Setup();

private:
	int			iKey;
	CService*	iService;
};

#endif
